apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels: 
    type: Frontend
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - name: nginx-deploy
        image: nginx:1.9.1
        ports:
        - containerPort: 80
        resources: {}
