
apiVersion: v1
kind: Pod
metadata:
  name: ed-pod
spec:
  containers:
  - image: alpine
    name: myvolumes-container-1
    command: ['sh', '-c', 'sleep 3600']
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /demo1
      name: demo-volume

  - image: alpine
    name: myvolumes-container-2
    command: ['sh', '-c', 'sleep 3600']
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /demo2
      name: demo-volume

  volumes:
  - name: demo-volume
    emptyDir: {}
    