apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-empty-dir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-empty-dir
  template:
    metadata:
      labels:
        app: shared-empty-dir
    spec:
      containers:
        - name: container1
          image: alpine
          command: ['sh', '-c', 'sleep 3600']
          volumeMounts:
            - name: shared-volume
              mountPath: /alpine1-data
        - name: container2
          image: alpine
          command: ['sh', '-c', 'sleep 3600']
          volumeMounts:
            - name: shared-volume
              mountPath: /alpine2-data
        - name: container3
          image: alpine
          command: ['sh', '-c', 'sleep 3600']
          volumeMounts:
            - name: shared-volume
              mountPath: /alpine3-data
      volumes:
        - name: shared-volume
          emptyDir: {}
