apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: alpine
        name: cm-container
        command: ['sh', '-c', 'while true; do echo Name: $NAME; Place: $PLACE; sleep 5; done']
        env:
        - name: NAME
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: name        
        - name: PLACE
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: place