apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  strategy: {}
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: alpine
        name: alpine
        command: ['sh', '-c', 'while true; do echo Name: $user; sleep 5; done']
        env:
        - name: user
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: USER
        resources: {}
status: {}
